
import React, { useState, useEffect } from 'react';
import Card from './GlassCard';
import { supabase } from '../services/supabaseClient';
import { UserProfile } from '../types';
import { DatabaseIcon, CodeIcon } from './icons';

interface DatabaseExplorerProps {
  userProfile: UserProfile;
}

const DatabaseExplorer: React.FC<DatabaseExplorerProps> = ({ userProfile }) => {
  const [activeTab, setActiveTab] = useState<'profiles' | 'tasks' | 'quizzes' | 'flashcard_sets' | 'file_chats' | 'setup'>('tasks');
  const [data, setData] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [queryInfo, setQueryInfo] = useState('');

  useEffect(() => {
    if (activeTab !== 'setup') {
        fetchData();
    }
  }, [activeTab, userProfile.id]);

  const fetchData = async () => {
    if (!supabase) return;
    setIsLoading(true);
    let result;
    
    try {
      setQueryInfo(`SELECT * FROM ${activeTab} WHERE user_id = '${userProfile.id}'`);
      
      if (activeTab === 'profiles') {
          setQueryInfo(`SELECT * FROM profiles WHERE id = '${userProfile.id}'`);
          result = await supabase.from('profiles').select('*').eq('id', userProfile.id);
      } else {
          result = await supabase.from(activeTab).select('*').eq('user_id', userProfile.id).order('created_at', { ascending: false });
      }

      if (result && !result.error) {
        setData(result.data);
      } else {
        setData([]);
      }
    } catch (err) {
      console.error(err);
    } finally {
      setIsLoading(false);
    }
  };

  const sqlSchema = `-- RUN THIS IN YOUR SUPABASE SQL EDITOR

-- 1. Profiles & Core Tables
CREATE TABLE profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  photo_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  text TEXT NOT NULL,
  completed BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE notes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID UNIQUE REFERENCES profiles(id) ON DELETE CASCADE,
  content TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. New Persistent Feature Tables
CREATE TABLE quizzes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  topic TEXT NOT NULL,
  score INTEGER,
  total_questions INTEGER,
  difficulty TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE flashcard_sets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  topic TEXT NOT NULL,
  cards JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE file_chats (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  file_name TEXT NOT NULL,
  messages JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Simple Policies (Enable RLS and allow public access for demo)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE quizzes ENABLE ROW LEVEL SECURITY;
ALTER TABLE flashcard_sets ENABLE ROW LEVEL SECURITY;
ALTER TABLE file_chats ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public" ON profiles FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public" ON tasks FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public" ON notes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public" ON quizzes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public" ON flashcard_sets FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public" ON file_chats FOR ALL USING (true) WITH CHECK (true);`;

  return (
    <Card className="h-full flex flex-col p-4 sm:p-6">
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center">
            <DatabaseIcon className="w-8 h-8 text-[var(--primary)] mr-3" />
            <h2 className="text-xl sm:text-2xl font-bold">Cloud Persistence Explorer</h2>
        </div>
        <button 
            onClick={() => setActiveTab('setup')}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg font-bold text-xs transition ${activeTab === 'setup' ? 'bg-[var(--accent)] text-white' : 'bg-[var(--accent)]/10 text-[var(--accent)]'}`}
        >
            <CodeIcon className="w-4 h-4" />
            Schema SQL
        </button>
      </div>

      <div className="flex flex-wrap gap-2 mb-6">
        {(['tasks', 'quizzes', 'flashcard_sets', 'file_chats', 'profiles'] as const).map(table => (
          <button
            key={table}
            onClick={() => setActiveTab(table)}
            className={`px-3 py-1.5 rounded-lg font-bold text-[10px] transition uppercase tracking-wider ${activeTab === table ? 'bg-[var(--primary)] text-white' : 'bg-[var(--input-bg)] text-[var(--foreground-muted)] hover:bg-[var(--primary)]/10'}`}
          >
            {table.replace('_', ' ')}
          </button>
        ))}
      </div>

      {activeTab === 'setup' ? (
        <div className="flex-grow flex flex-col overflow-hidden">
            <div className="relative flex-grow">
                <pre className="h-full p-4 bg-slate-900 rounded-lg font-mono text-xs text-green-400 overflow-auto border border-slate-700">
                    {sqlSchema}
                </pre>
                <button onClick={() => {navigator.clipboard.writeText(sqlSchema); alert("SQL Copied!");}} className="absolute top-4 right-4 bg-white/10 text-white px-3 py-1 rounded text-xs">Copy</button>
            </div>
        </div>
      ) : (
        <div className="flex-grow overflow-auto border border-[var(--card-border)] rounded-xl bg-black/5">
            {isLoading ? <div className="flex items-center justify-center h-full"><div className="loader"></div></div> : (
                <table className="w-full text-left text-[10px] sm:text-xs">
                    <thead className="bg-[var(--card-bg)] sticky top-0">
                        <tr>{data.length > 0 && Object.keys(data[0]).map(key => <th key={key} className="p-2 border-b border-[var(--card-border)] uppercase font-bold text-[var(--foreground-muted)]">{key}</th>)}</tr>
                    </thead>
                    <tbody>
                        {data.map((row, i) => <tr key={i} className="border-b border-[var(--card-border)]/50 hover:bg-white/5">{Object.values(row).map((val: any, j) => <td key={j} className="p-2 max-w-[150px] truncate">{typeof val === 'object' ? 'JSON Data' : String(val)}</td>)}</tr>)}
                    </tbody>
                </table>
            )}
        </div>
      )}
    </Card>
  );
};

export default DatabaseExplorer;
